#define NUMBER_OF_TRANSACTIONS_PER_TICK 1024
#define SIGNATURE_SIZE 64
#define SPECTRUM_DEPTH 24 // Is derived from SPECTRUM_CAPACITY (=N)
#define DEFAULT_SEED ((char *)"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
#define QX_ADDRESS ((char *)"BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARMID")
#define ARBITRATOR ((char *)"AFZPUAIYVPNUYGJRQVLUKOPPVLHAZQTGLYAAUUNBXFTVTAMSBKQBLEIEPCVJ")
#define NUMBER_OF_COMPUTORS 676

#define EXCHANGE_PUBLIC_PEERS 0
#define BROADCAST_COMPUTORS 2
#define BROADCAST_TICK 3
#define BROADCAST_FUTURE_TICK_DATA 8
#define REQUEST_COMPUTORS 11
#define REQUEST_QUORUMTICK 14
#define REQUEST_TICK_DATA 16
#define BROADCAST_TRANSACTION 24
#define REQUEST_CURRENT_TICK_INFO 27
#define RESPOND_CURRENT_TICK_INFO 28
#define REQUEST_TICK_TRANSACTIONS 29
#define REQUEST_ENTITY 31
#define RESPOND_ENTITY 32
#define PROCESS_SPECIAL_COMMAND 255
#define REQUEST_ISSUED_ASSETS 36
#define RESPOND_ISSUED_ASSETS 37
#define REQUEST_OWNED_ASSETS 38
#define RESPOND_OWNED_ASSETS 39
#define REQUEST_POSSESSED_ASSETS 40
#define RESPOND_POSSESSED_ASSETS 41

#define QX_CONTRACT_INDEX 1
#define QX_FEE_FUNCTION_INDEX 1
#define QTRY_CONTRACT_ID 2
#define RANDOM_CONTRACT_ID 3

#define RANDOM_CONTRACT_ID 3
#define RANDOM_REVEALCOMMIT 1

// SENDMANY DEFINES
#define QUTIL_CONTRACT_ID 4
#define SENDTOMANYV1 1
#define SENDMANYFEE 10
#define MAXENTITY_PERSECOND 1024
#define MAXSENDMANY_PERTICK 100
#define MAXFANS (FAN*FAN*FAN + FAN*FAN + FAN + 1)

char *randpeer(char *ipaddr);

